"""Correctness tests for zerodep png module.

Apple-to-apple validation against Pillow as reference implementation.
"""

import io
import math
import os
import random
import struct
import sys

import pytest

sys.path.insert(0, os.path.dirname(__file__))

from png import (
    DecodeError,
    EncodeError,
    Image,
    convert,
    decode_bmp,
    decode_png,
    encode_bmp,
    encode_png,
    matrix_to_png,
    png_to_matrix,
)

PIL_Image = pytest.importorskip("PIL.Image")


# ============================================================================
# Helpers
# ============================================================================


def _make_test_image(mode, width, height, seed=42):
    """Create a deterministic test image. Returns (PILImage, raw_pixels)."""
    rng = random.Random(seed)
    bpp = {"L": 1, "LA": 2, "RGB": 3, "RGBA": 4}[mode]
    pixels = bytes(rng.randint(0, 255) for _ in range(width * height * bpp))
    pil = PIL_Image.frombytes(mode, (width, height), pixels)
    return pil, pixels


def _pil_to_png(pil_img):
    buf = io.BytesIO()
    pil_img.save(buf, format="PNG")
    return buf.getvalue()


def _pil_to_bmp(pil_img):
    buf = io.BytesIO()
    pil_img.save(buf, format="BMP")
    return buf.getvalue()


def _assert_pixels_equal(actual, expected, msg=""):
    assert len(actual) == len(expected), (
        f"length mismatch{': ' + msg if msg else ''}: {len(actual)} vs {len(expected)}"
    )
    if actual != expected:
        idx = next(i for i, (a, b) in enumerate(zip(actual, expected)) if a != b)
        pytest.fail(
            f"pixel mismatch{': ' + msg if msg else ''} "
            f"at byte {idx}: {actual[idx]} vs {expected[idx]}"
        )


# ============================================================================
# PNG Decode — Pillow-generated PNGs decoded by zerodep
# ============================================================================

MODES_8BIT = ["L", "LA", "RGB", "RGBA"]
SIZES = [(1, 1), (8, 8), (64, 64), (256, 256)]


class TestPngDecodeVsPillow:
    """Decode Pillow-generated PNGs with zerodep, compare pixel data."""

    @pytest.mark.parametrize("mode", MODES_8BIT)
    @pytest.mark.parametrize("size", SIZES, ids=lambda s: f"{s[0]}x{s[1]}")
    def test_decode_8bit(self, mode, size):
        w, h = size
        pil, expected = _make_test_image(mode, w, h)
        png_bytes = _pil_to_png(pil)

        img = decode_png(png_bytes)
        assert img.width == w
        assert img.height == h
        assert img.mode == mode
        assert img.bit_depth == 8
        _assert_pixels_equal(img.data, expected, f"{mode} {w}x{h}")

    def test_decode_16bit_gray(self):
        """16-bit grayscale PNG generated by Pillow."""
        w, h = 32, 32
        rng = random.Random(99)
        values = [rng.randint(0, 65535) for _ in range(w * h)]

        # Pillow I;16 uses little-endian storage
        le_bytes = b"".join(struct.pack("<H", v) for v in values)
        pil = PIL_Image.frombytes("I;16", (w, h), le_bytes)
        png_bytes = _pil_to_png(pil)

        img = decode_png(png_bytes)
        assert img.mode == "L"
        assert img.bit_depth == 16

        # PNG stores 16-bit as big-endian
        expected_be = b"".join(struct.pack(">H", v) for v in values)
        _assert_pixels_equal(img.data, expected_be, "16-bit L")


# ============================================================================
# PNG Encode — zerodep encodes, Pillow decodes to verify
# ============================================================================

FILTER_STRATEGIES = ["auto", "none", "sub", "up", "avg", "paeth"]


class TestPngEncodeVsPillow:
    """Encode with zerodep, decode with Pillow, compare pixel data."""

    @pytest.mark.parametrize("mode", MODES_8BIT)
    @pytest.mark.parametrize("strategy", FILTER_STRATEGIES)
    def test_encode_filter_strategies(self, mode, strategy):
        w, h = 32, 32
        _, pixels = _make_test_image(mode, w, h)
        img = Image(width=w, height=h, data=pixels, mode=mode)

        png_bytes = encode_png(img, filter_strategy=strategy)
        pil = PIL_Image.open(io.BytesIO(png_bytes))
        assert pil.mode == mode
        _assert_pixels_equal(pil.tobytes(), pixels, f"{mode} filter={strategy}")

    @pytest.mark.parametrize("size", SIZES, ids=lambda s: f"{s[0]}x{s[1]}")
    def test_encode_rgba_sizes(self, size):
        w, h = size
        _, pixels = _make_test_image("RGBA", w, h)
        img = Image(width=w, height=h, data=pixels, mode="RGBA")

        png_bytes = encode_png(img)
        pil = PIL_Image.open(io.BytesIO(png_bytes))
        _assert_pixels_equal(pil.tobytes(), pixels, f"RGBA {w}x{h}")

    def test_encode_metadata(self):
        """tEXt metadata survives encode -> Pillow decode."""
        w, h = 8, 8
        _, pixels = _make_test_image("L", w, h)
        meta = {"Author": "zerodep", "Comment": "test image"}
        img = Image(width=w, height=h, data=pixels, mode="L", metadata=meta)

        png_bytes = encode_png(img)
        pil = PIL_Image.open(io.BytesIO(png_bytes))
        pil_text = getattr(pil, "text", {}) or pil.info
        for key, val in meta.items():
            assert pil_text.get(key) == val, f"metadata key {key!r} missing"


# ============================================================================
# PNG Round-trip (self-verification, no Pillow dependency)
# ============================================================================


class TestPngRoundTrip:
    """Encode -> decode round-trip with zerodep only."""

    @pytest.mark.parametrize("mode", MODES_8BIT)
    def test_roundtrip_8bit(self, mode):
        w, h = 48, 48
        _, pixels = _make_test_image(mode, w, h)
        original = Image(width=w, height=h, data=pixels, mode=mode)

        decoded = decode_png(encode_png(original))
        assert decoded.width == w
        assert decoded.height == h
        assert decoded.mode == mode
        assert decoded.bit_depth == 8
        _assert_pixels_equal(decoded.data, pixels)

    def test_roundtrip_16bit(self):
        w, h = 16, 16
        rng = random.Random(77)
        pixels = b"".join(
            struct.pack(">H", rng.randint(0, 65535)) for _ in range(w * h)
        )
        original = Image(width=w, height=h, data=pixels, mode="L", bit_depth=16)

        decoded = decode_png(encode_png(original))
        assert decoded.bit_depth == 16
        _assert_pixels_equal(decoded.data, pixels)

    @pytest.mark.parametrize("strategy", FILTER_STRATEGIES)
    def test_roundtrip_filters(self, strategy):
        w, h = 32, 32
        _, pixels = _make_test_image("RGBA", w, h)
        original = Image(width=w, height=h, data=pixels, mode="RGBA")

        decoded = decode_png(encode_png(original, filter_strategy=strategy))
        _assert_pixels_equal(decoded.data, pixels, f"filter={strategy}")

    def test_roundtrip_metadata(self):
        w, h = 4, 4
        _, pixels = _make_test_image("L", w, h)
        meta = {"Author": "test", "Description": "round-trip metadata test"}
        original = Image(width=w, height=h, data=pixels, mode="L", metadata=meta)

        decoded = decode_png(encode_png(original))
        assert decoded.metadata == meta


# ============================================================================
# BMP Decode — Pillow-generated BMPs decoded by zerodep
# ============================================================================


class TestBmpDecodeVsPillow:
    """Decode Pillow-generated BMPs with zerodep."""

    @pytest.mark.parametrize(
        "size",
        [(1, 1), (8, 8), (13, 7), (64, 64), (256, 256)],
        ids=lambda s: f"{s[0]}x{s[1]}",
    )
    def test_decode_rgb(self, size):
        w, h = size
        pil, expected = _make_test_image("RGB", w, h)
        bmp_bytes = _pil_to_bmp(pil)

        img = decode_bmp(bmp_bytes)
        assert img.width == w
        assert img.height == h
        assert img.mode == "RGB"
        _assert_pixels_equal(img.data, expected, f"BMP RGB {w}x{h}")

    def test_decode_rgba(self):
        w, h = 32, 32
        pil, expected = _make_test_image("RGBA", w, h)
        bmp_bytes = _pil_to_bmp(pil)

        img = decode_bmp(bmp_bytes)
        assert img.width == w
        assert img.height == h
        assert img.mode == "RGBA"
        _assert_pixels_equal(img.data, expected, "BMP RGBA")


# ============================================================================
# BMP Encode — zerodep encodes, Pillow decodes
# ============================================================================


class TestBmpEncodeVsPillow:
    """Encode BMP with zerodep, decode with Pillow."""

    @pytest.mark.parametrize(
        "size",
        [(8, 8), (11, 5), (64, 64), (256, 256)],
        ids=lambda s: f"{s[0]}x{s[1]}",
    )
    def test_encode_rgb(self, size):
        w, h = size
        _, pixels = _make_test_image("RGB", w, h)
        img = Image(width=w, height=h, data=pixels, mode="RGB")

        bmp_bytes = encode_bmp(img)
        pil = PIL_Image.open(io.BytesIO(bmp_bytes)).convert("RGB")
        _assert_pixels_equal(pil.tobytes(), pixels, f"BMP encode RGB {w}x{h}")

    def test_encode_rgba(self):
        # BMP with 40-byte DIB header has no alpha mask — Pillow reads the
        # 4th byte as reserved (sets alpha=255).  Compare RGB channels only.
        w, h = 32, 32
        _, pixels = _make_test_image("RGBA", w, h)
        img = Image(width=w, height=h, data=pixels, mode="RGBA")

        bmp_bytes = encode_bmp(img)
        pil = PIL_Image.open(io.BytesIO(bmp_bytes)).convert("RGB")
        expected_rgb = bytes(
            pixels[i + c] for i in range(0, len(pixels), 4) for c in range(3)
        )
        _assert_pixels_equal(pil.tobytes(), expected_rgb, "BMP encode RGBA (RGB only)")


# ============================================================================
# BMP Round-trip (self-verification)
# ============================================================================


class TestBmpRoundTrip:
    """BMP encode -> decode round-trip."""

    @pytest.mark.parametrize("mode", ["RGB", "RGBA"])
    def test_roundtrip(self, mode):
        w, h = 40, 40
        _, pixels = _make_test_image(mode, w, h)
        original = Image(width=w, height=h, data=pixels, mode=mode)

        decoded = decode_bmp(encode_bmp(original))
        assert decoded.mode == mode
        _assert_pixels_equal(decoded.data, pixels, f"BMP roundtrip {mode}")


# ============================================================================
# Cross-format round-trip (PNG <-> BMP)
# ============================================================================


class TestCrossFormat:
    """PNG <-> BMP conversion preserves pixel data."""

    def test_png_to_bmp_to_png(self):
        w, h = 32, 32
        _, pixels = _make_test_image("RGB", w, h)
        img = Image(width=w, height=h, data=pixels, mode="RGB")

        from_png = decode_png(encode_png(img))
        from_bmp = decode_bmp(encode_bmp(from_png))
        _assert_pixels_equal(from_bmp.data, pixels)

    def test_bmp_to_png_to_bmp(self):
        w, h = 32, 32
        _, pixels = _make_test_image("RGBA", w, h)
        img = Image(width=w, height=h, data=pixels, mode="RGBA")

        from_bmp = decode_bmp(encode_bmp(img))
        from_png = decode_png(encode_png(from_bmp))
        _assert_pixels_equal(from_png.data, pixels)


# ============================================================================
# Mode conversion vs Pillow
# ============================================================================

# Conversions where both implementations should match exactly (no luminosity)
EXACT_CONVERSIONS = [
    ("L", "RGB"),
    ("L", "RGBA"),
    ("L", "LA"),
    ("LA", "L"),
    ("RGB", "RGBA"),
    ("RGBA", "RGB"),
]

# Conversions involving luminosity — allow +/-1 rounding difference
APPROX_CONVERSIONS = [
    ("RGB", "L"),
    ("RGB", "LA"),
    ("RGBA", "L"),
    ("RGBA", "LA"),
    ("LA", "RGB"),
    ("LA", "RGBA"),
]


class TestConvert:
    """Test mode conversion against Pillow's convert."""

    @pytest.mark.parametrize("src,dst", EXACT_CONVERSIONS)
    def test_exact(self, src, dst):
        w, h = 16, 16
        pil, pixels = _make_test_image(src, w, h)
        img = Image(width=w, height=h, data=pixels, mode=src)

        converted = convert(img, dst)
        expected = pil.convert(dst).tobytes()
        _assert_pixels_equal(converted.data, expected, f"{src}->{dst}")

    @pytest.mark.parametrize("src,dst", APPROX_CONVERSIONS)
    def test_approx(self, src, dst):
        w, h = 16, 16
        pil, pixels = _make_test_image(src, w, h)
        img = Image(width=w, height=h, data=pixels, mode=src)

        converted = convert(img, dst)
        expected = pil.convert(dst).tobytes()
        max_diff = max(abs(a - b) for a, b in zip(converted.data, expected))
        assert max_diff <= 1, f"{src}->{dst} max pixel diff {max_diff} > 1"

    def test_noop(self):
        _, pixels = _make_test_image("RGB", 8, 8)
        img = Image(width=8, height=8, data=pixels, mode="RGB")
        result = convert(img, "RGB")
        _assert_pixels_equal(result.data, pixels)
        assert result is not img


# ============================================================================
# Matrix API
# ============================================================================


class TestMatrixApi:
    """Test matrix_to_png / png_to_matrix round-trips."""

    def test_uint8_roundtrip(self):
        matrix = [[i * 17 + j for j in range(16)] for i in range(15)]
        result = png_to_matrix(matrix_to_png(matrix))
        assert result == matrix

    def test_uint16_roundtrip(self):
        matrix = [[i * 4096 + j * 16 for j in range(32)] for i in range(16)]
        result = png_to_matrix(matrix_to_png(matrix, bit_depth=16))
        assert result == matrix

    def test_float_roundtrip_8bit(self):
        matrix = [[math.sin(x * 0.1 + y * 0.2) for x in range(32)] for y in range(32)]
        result = png_to_matrix(matrix_to_png(matrix))

        vmin = min(min(r) for r in matrix)
        vmax = max(max(r) for r in matrix)
        tol = (vmax - vmin) / 255 + 1e-9
        for y in range(len(matrix)):
            for x in range(len(matrix[0])):
                assert abs(result[y][x] - matrix[y][x]) <= tol

    def test_float_roundtrip_16bit(self):
        matrix = [
            [math.sin(x * 0.1 + y * 0.2) * 1000 for x in range(16)] for y in range(16)
        ]
        result = png_to_matrix(matrix_to_png(matrix, bit_depth=16))

        vmin = min(min(r) for r in matrix)
        vmax = max(max(r) for r in matrix)
        tol = (vmax - vmin) / 65535 + 1e-9
        for y in range(len(matrix)):
            for x in range(len(matrix[0])):
                assert abs(result[y][x] - matrix[y][x]) <= tol

    def test_constant_matrix(self):
        matrix = [[42] * 8 for _ in range(8)]
        result = png_to_matrix(matrix_to_png(matrix))
        assert result == matrix

    def test_negative_values(self):
        matrix = [[-10, 0, 10], [-5, 5, 15]]
        result = png_to_matrix(matrix_to_png(matrix))
        assert isinstance(result[0][0], float)

    def test_empty_raises(self):
        with pytest.raises(EncodeError):
            matrix_to_png([])
        with pytest.raises(EncodeError):
            matrix_to_png([[]])


# ============================================================================
# Error cases
# ============================================================================


class TestErrorCases:
    """Invalid inputs raise appropriate errors."""

    def test_truncated_png(self):
        _, pixels = _make_test_image("RGB", 8, 8)
        png_bytes = encode_png(Image(width=8, height=8, data=pixels, mode="RGB"))
        with pytest.raises(DecodeError):
            decode_png(png_bytes[:20])

    def test_bad_png_signature(self):
        with pytest.raises(DecodeError, match="bad signature"):
            decode_png(b"NOT A PNG FILE" + b"\x00" * 100)

    def test_bad_bmp_signature(self):
        with pytest.raises(DecodeError, match="bad signature"):
            decode_bmp(b"XX" + b"\x00" * 100)

    def test_bmp_too_small(self):
        with pytest.raises(DecodeError):
            decode_bmp(b"BM" + b"\x00" * 10)

    def test_invalid_mode(self):
        with pytest.raises(ValueError, match="unsupported mode"):
            Image(width=1, height=1, data=b"\x00", mode="CMYK")

    def test_invalid_bit_depth(self):
        with pytest.raises(ValueError, match="unsupported bit_depth"):
            Image(width=1, height=1, data=b"\x00", mode="L", bit_depth=4)

    def test_data_length_mismatch(self):
        with pytest.raises(ValueError, match="data length"):
            Image(width=2, height=2, data=b"\x00\x01\x02", mode="L")

    def test_bmp_encode_unsupported_mode(self):
        img = Image(width=1, height=1, data=b"\x00", mode="L")
        with pytest.raises(EncodeError, match="RGB or RGBA"):
            encode_bmp(img)

    def test_encode_unknown_filter(self):
        img = Image(width=1, height=1, data=b"\x00\x00\x00", mode="RGB")
        with pytest.raises(EncodeError, match="unknown filter_strategy"):
            encode_png(img, filter_strategy="invalid")

    def test_convert_unsupported_target(self):
        img = Image(width=1, height=1, data=b"\x00", mode="L")
        with pytest.raises(ValueError, match="unsupported target mode"):
            convert(img, "CMYK")

    def test_convert_16bit_raises(self):
        pixels = struct.pack(">H", 1000)
        img = Image(width=1, height=1, data=pixels, mode="L", bit_depth=16)
        with pytest.raises(ValueError, match="8-bit"):
            convert(img, "RGB")
