#!/usr/bin/env python3
"""Generate modules/index.md for both EN and ZH docs from manifest + config.

Reads ``manifest.json`` for runtime data (version, last_updated, deps) and
``scripts/module_index_config.yaml`` for doc-specific metadata (categories,
descriptions, benchmarks).  Produces deterministic markdown that can be
diffed or checked in CI with ``--check``.

Usage::

    python scripts/generate_module_index.py            # write both index files
    python scripts/generate_module_index.py --check     # exit 1 if files differ
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _import_yaml_load():
    """Import the project's own yaml parser, avoiding stdlib name collision."""
    spec = importlib.util.spec_from_file_location(
        "zerodep_yaml", REPO_ROOT / "yaml" / "yaml.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.load


yaml_load = _import_yaml_load()

# ── Defaults ──

DEFAULT_MANIFEST = REPO_ROOT / "manifest.json"
DEFAULT_CONFIG = REPO_ROOT / "scripts" / "module_index_config.yaml"
DEFAULT_OUT_EN = REPO_ROOT / "docs_en" / "docs" / "modules" / "index.md"
DEFAULT_OUT_ZH = REPO_ROOT / "docs_zh" / "docs" / "modules" / "index.md"

GENERATED_HEADER = (
    "<!-- AUTO-GENERATED by scripts/generate_module_index.py — DO NOT EDIT -->\n"
)

# ── Bilingual text ──

TEXT: dict[str, dict[str, str | tuple[str, ...]]] = {
    "en": {
        "title": "Module Overview",
        "heading": "Module Overview",
        "intro": (
            "Each zerodep module is a **self-contained single `.py` file** "
            "that you can copy directly into your project. "
            "No `pip install` required at runtime."
        ),
        "status_heading": "Module Status",
        "status_cols": ("Module", "Version", "Last Updated"),
        "all_heading": "All Modules",
        "module_cols": ("Module", "Description", "Benchmark Against"),
        "deps_heading": "Inter-Module Dependencies",
        "deps_intro": (
            "Most zerodep modules are fully standalone. "
            "The following modules depend on other zerodep modules:"
        ),
        "deps_footer": (
            "When using the [CLI tool](../guide/cli.md), dependencies are "
            "resolved automatically. For manual installation, ensure all "
            "required modules are present."
        ),
    },
    "zh": {
        "title": "模块概览",
        "heading": "模块概览",
        "intro": (
            "每个 zerodep 模块都是一个**独立的单 `.py` 文件**，"
            "可以直接复制到你的项目中使用，运行时无需 `pip install`。"
        ),
        "status_heading": "模块状态",
        "status_cols": ("模块", "版本", "最后更新"),
        "all_heading": "全部模块",
        "module_cols": ("模块", "描述", "性能对标"),
        "deps_heading": "模块间依赖关系",
        "deps_intro": (
            "大部分 zerodep 模块是完全独立的。以下模块依赖其他 zerodep 模块："
        ),
        "deps_footer": (
            "使用 [CLI 工具](../guide/cli.md) 时，依赖会自动解析。"
            "手动安装时，请确保所有依赖模块都已就位。"
        ),
    },
}

# ── Data structures ──


@dataclass
class ModuleInfo:
    """Merged module metadata from manifest + config."""

    name: str
    version: str = "0.0.0"
    last_updated: str = "\u2014"
    deps: list[str] = field(default_factory=list)
    doc_page: str = ""
    benchmark: str | None = None
    desc_en: str = ""
    desc_zh: str = ""

    def __post_init__(self) -> None:
        if not self.doc_page:
            self.doc_page = f"{self.name}.md"


@dataclass
class Category:
    """A doc category with display names and ordered member list."""

    id: str
    name_en: str
    name_zh: str
    modules: list[str]


# ── Loading ──


def load_manifest(path: Path) -> dict:
    """Load manifest.json."""
    return json.loads(path.read_text(encoding="utf-8"))


def load_config(path: Path) -> tuple[list[Category], dict[str, dict]]:
    """Load the YAML config and return (categories, module_meta)."""
    raw = yaml_load(path.read_text(encoding="utf-8"))

    categories = [
        Category(
            id=c["id"],
            name_en=c["name_en"],
            name_zh=c["name_zh"],
            modules=c["modules"],
        )
        for c in raw["categories"]
    ]
    module_meta = raw.get("modules", {})
    return categories, module_meta


# ── Validation ──


def validate(
    categories: list[Category],
    module_meta: dict[str, dict],
    manifest_modules: dict[str, dict],
) -> set[str]:
    """Cross-reference config and manifest.  Returns configured module names.

    Prints warnings/errors to stderr.  Returns the set of module names that
    appear in at least one category's modules list.
    """
    errors = 0

    # All module names referenced by categories
    configured: set[str] = set()
    for cat in categories:
        for name in cat.modules:
            configured.add(name)

    # Every category module must have a config entry
    for name in sorted(configured):
        if name not in module_meta:
            print(
                f"error: module {name!r} in category list but missing "
                f"from config modules section",
                file=sys.stderr,
            )
            errors += 1

    # Every config module entry must be in a category
    for name in sorted(module_meta):
        if name not in configured:
            print(
                f"error: module {name!r} in config modules section but "
                f"not in any category list",
                file=sys.stderr,
            )
            errors += 1

    # Every configured module must exist in manifest
    for name in sorted(configured):
        if name not in manifest_modules:
            print(
                f"error: module {name!r} in config but not in manifest.json "
                f"(run 'make manifest'?)",
                file=sys.stderr,
            )
            errors += 1

    # Warn about manifest modules not in config (WIP modules)
    for name in sorted(manifest_modules):
        if name not in configured:
            print(
                f"warning: module {name!r} in manifest but not in config "
                f"(excluded from docs index)",
                file=sys.stderr,
            )

    if errors:
        print(f"\n{errors} error(s) found, aborting.", file=sys.stderr)
        sys.exit(1)

    return configured


# ── Merging ──


def build_modules(
    configured: set[str],
    module_meta: dict[str, dict],
    manifest_modules: dict[str, dict],
) -> dict[str, ModuleInfo]:
    """Merge manifest + config into ModuleInfo objects."""
    result: dict[str, ModuleInfo] = {}
    for name in sorted(configured):
        m = manifest_modules[name]
        meta = module_meta[name]

        # Parse last_updated to date-only
        ts = m.get("last_updated")
        if ts:
            date_str = ts.split("T")[0]
        else:
            date_str = "\u2014"

        result[name] = ModuleInfo(
            name=name,
            version=m.get("version", "0.0.0"),
            last_updated=date_str,
            deps=m.get("deps", []),
            doc_page=meta.get("doc_page", f"{name}.md"),
            benchmark=meta.get("benchmark"),
            desc_en=meta.get("desc_en", ""),
            desc_zh=meta.get("desc_zh", ""),
        )
    return result


# ── Rendering ──


def _fmt_benchmark(benchmark: str | None) -> str:
    """Format a benchmark value for the table."""
    if benchmark:
        return f"`{benchmark}`"
    return "--"


def render_index(
    lang: str,
    categories: list[Category],
    modules: dict[str, ModuleInfo],
) -> str:
    """Render a full index.md document."""
    t = TEXT[lang]
    lines: list[str] = []

    # Header comment
    lines.append(GENERATED_HEADER)

    # Frontmatter
    lines.append("---")
    lines.append(f"title: {t['title']}")
    lines.append("---")
    lines.append("")

    # Heading + intro
    lines.append(f"# {t['heading']}")
    lines.append("")
    lines.append(str(t["intro"]))
    lines.append("")

    # Module Status table
    lines.append(f"## {t['status_heading']}")
    lines.append("")
    cols = t["status_cols"]
    assert isinstance(cols, tuple)
    lines.append(f"| {cols[0]} | {cols[1]} | {cols[2]} |")
    lines.append("|--------|---------|--------------|")
    for name in sorted(modules):
        mod = modules[name]
        link = f"[{name}]({mod.doc_page})"
        lines.append(f"| {link} | {mod.version} | {mod.last_updated} |")
    lines.append("")

    # All Modules by category
    lines.append(f"## {t['all_heading']}")
    lines.append("")
    mcols = t["module_cols"]
    assert isinstance(mcols, tuple)
    for cat in categories:
        cat_name = cat.name_en if lang == "en" else cat.name_zh
        lines.append(f"### {cat_name}")
        lines.append("")
        lines.append(f"| {mcols[0]} | {mcols[1]} | {mcols[2]} |")
        lines.append("|--------|-------------|-------------------|")
        for mod_name in cat.modules:
            mod = modules[mod_name]
            link = f"[{mod_name}]({mod.doc_page})"
            desc = mod.desc_en if lang == "en" else mod.desc_zh
            bench = _fmt_benchmark(mod.benchmark)
            lines.append(f"| {link} | {desc} | {bench} |")
        lines.append("")

    # Inter-Module Dependencies
    lines.append(f"## {t['deps_heading']}")
    lines.append("")
    lines.append(str(t["deps_intro"]))
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")

    # Collect and sort edges
    edges: list[str] = []
    configured_names = {mod.name for mod in modules.values()}
    for mod in modules.values():
        for dep in mod.deps:
            if dep in configured_names:
                edges.append(f"    {mod.name} --> {dep}")
    for edge in sorted(edges):
        lines.append(edge)

    lines.append("```")
    lines.append("")
    lines.append(str(t["deps_footer"]))
    lines.append("")

    return "\n".join(lines)


# ── Output ──


def write_or_check(path: Path, content: str, *, check: bool) -> bool:
    """Write content to path, or compare in check mode.

    Returns True if the file is up-to-date (or was written successfully).
    """
    if check:
        if not path.exists():
            print(f"FAIL: {path} does not exist", file=sys.stderr)
            return False
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return True
        # Find first differing line
        existing_lines = existing.splitlines()
        content_lines = content.splitlines()
        for i, (a, b) in enumerate(zip(existing_lines, content_lines), 1):
            if a != b:
                print(
                    f"FAIL: {path} differs at line {i}:\n"
                    f"  existing: {a!r}\n"
                    f"  expected: {b!r}",
                    file=sys.stderr,
                )
                return False
        # Length difference
        if len(existing_lines) != len(content_lines):
            print(
                f"FAIL: {path} has {len(existing_lines)} lines, "
                f"expected {len(content_lines)}",
                file=sys.stderr,
            )
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")
    return True


# ── CLI ──


def main(argv: list[str] | None = None) -> None:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Generate modules/index.md for EN and ZH docs.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="path to manifest.json",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help="path to module_index_config.yaml",
    )
    parser.add_argument(
        "--out-en",
        type=Path,
        default=DEFAULT_OUT_EN,
        help="output path for EN index.md",
    )
    parser.add_argument(
        "--out-zh",
        type=Path,
        default=DEFAULT_OUT_ZH,
        help="output path for ZH index.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated output with existing files, exit 1 if different",
    )
    parser.add_argument(
        "--lang",
        choices=["en", "zh", "all"],
        default="all",
        help="which language(s) to generate (default: all)",
    )
    args = parser.parse_args(argv)

    # Load
    manifest = load_manifest(args.manifest)
    manifest_modules = manifest.get("modules", {})
    categories, module_meta = load_config(args.config)

    # Validate
    configured = validate(categories, module_meta, manifest_modules)

    # Build
    modules = build_modules(configured, module_meta, manifest_modules)

    # Render + output
    ok = True
    if args.lang in ("en", "all"):
        en_content = render_index("en", categories, modules)
        ok = write_or_check(args.out_en, en_content, check=args.check) and ok
    if args.lang in ("zh", "all"):
        zh_content = render_index("zh", categories, modules)
        ok = write_or_check(args.out_zh, zh_content, check=args.check) and ok

    if args.check:
        if ok:
            print("OK: index file(s) up-to-date")
        else:
            sys.exit(1)


if __name__ == "__main__":
    main()
